# Generated by Django 5.1.3 on 2024-12-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signature',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('pendente', 'Pendente'), ('expirada', 'Expirada')], default='pendente', max_length=10),
        ),
    ]
