# Generated by Django 5.1.3 on 2024-12-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_alter_signature_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='resource',
        ),
    ]
