# Generated by Django 5.1.3 on 2024-12-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_flat_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descripition',
            new_name='description',
        ),
    ]
