# Generated by Django 5.1.3 on 2024-12-09 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_descripition_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signature',
            name='flat',
        ),
        migrations.RemoveField(
            model_name='signature',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='Signature',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
